Blog Page Redesign and Console Launch Button (#232)
* Refactored code to update the page title and banner link. Applied light color to the header and paragraph description( 3 groups ) for improved visibility on mobile screens in dark mode.

* Style: Applied light color to the header text and paragraph description( 3 groups ) for improved visibility on larger  screens in dark mode.

Style:  added hovers to Buttons in GPU-Testnet Page and refactored some of the css ro make it readable.

* 1. Reduced width of the main titles to prevent text overlaps.

2.Updated the top-level red link banner to open a new tab when the user clicks.

* Style: refactored the css file to make it organize and readable.

* GPU-Testnet Page Update: Date updated from "June 12, 2023 - Ends: July 3rd, 2023" to "June 20th, 2023 - Ends: July 11th, 2023 "
1. GPU docs links added successfuly,
2. kyc guideline button removed. 3. Gpu table caption and horizontal line  removed.
4.Updated the introductory text to provide a clearer description of the open-source marketplace for GPU compute.

* Style: Space added  around the GPU Models (top, left, bottom).

* 1. Fixed font issue on the community page for dark mode
2. Updated GPU docs link

* Styles: Refactored the css in dark mode to make it readable

* Updated Token page: added SVG illustrations and implemented new design layout

* merge remote tracking

* Updated Hugo image processor and increased blog image quality by 95. Added styling to blog header

* update

* Blog page improved, update on homepage blog section cards

* Refactored the css to make it readable

* Style: added  a font-size to bog-title

* feat(section): Added scroll interactions to the 3 groups sections

* a click event added to 3 groups

* Feat:  fixed scrolling error on 3 groups section

* Data labelling error fixed on small screen

* refactored css to make it readable

* Feat: Red bar announcement alert removed

* Feat: Arrow added to nav menus that open a new a tab, Launch console button successfully added

* Feat: Code cleanup and improvement on mobile and tablet devices

* Feat: three groups functionality improved

* Feat: 3 groups scroll error fixed

* Feat: Refactored css to make it readable

* update

* update

* Feat: Homepage code refactored to make it readable

* Feat: refactored token page

* Feat: pagination error fixed

* Feat: Blog page hero section added

* Feat: pagination errors fixed

* Feat: main blog details page styles changed and refactored

* Feat: share blog on twitter added

* Feat: new styles and card implememted on contributors, categories and tags page.
Error: animated gif error fixed

* Feat: cards image optimized

* Feat: Lazyload added to blog cards

* update

* Feat: blog card image optimization

* update on card optimization

* update

* Feat: card optimization

* update

* update

* Feat: blog cards responsiveness fixed

* Feat: Blog page responsiveness improve

* Feat: Homescreen cards width fixed and responsiveness improved

* Feat: newsletter section text updated

* Feat:  darkmode svg colors added

* Feat: pagination width fixed on mobile screen

* Feat: three dotten horizontal removed from navbar

* update

* Feat: ecosystem tools on dark mode color changed to white

* Feat: newsletter width fixed

* update

* Feat: css file created for newsletter styles

* Feat: data and time font-weight  change to 500 newsletter covers full width

* Feat: social icons added

* Feat: testing social links

* Feat: Linkedin url added

* Style: dark mode style added for social svgs

* update

---------

Signed-off-by: Arthur Emmanuel <86601468+ArthurEmma2@users.noreply.github.com>